In [2]:
import numpy as np
import parameters as p
from sympy import ntt, intt

In [3]:
class ConVolution:
    def __init__(self):
        pass

    def con2d(self, a, w):
        A = np.mat(a)
        W = np.mat(w)
        U = np.mat(np.zeros((p.con_size-p.kernel_size+1, p.con_size-p.kernel_size+1), dtype='int32'))
        rows, cols = A.shape
        for i in range(rows-1):
            for j in range(cols-1):
                U[i,j] = np.multiply(A[i:(i+p.kernel_size),j:(j+p.kernel_size)], W).sum()
                #print(np.multiply(A[i:(i+kernel_size),j:(j+kernel_size)], W))
        return U

    def trim(self, raw):
        raw = raw[(p.con_size*(p.kernel_size-1)+p.kernel_size-2):(p.con_size**2)][::-1]
        result = raw.reshape((p.out_size,p.con_size))[:,0:p.out_size]
        return result

    def shape(self, a, w):
        w_bar = np.zeros_like(a)
        a_bar = a.flatten()[::-1]
        w_bar[0:p.kernel_size,0:p.kernel_size] = w
        w_bar = w_bar.flatten()
        return a_bar, w_bar

    def con1d(self, a, w):
        a_bar, w_bar = self.shape(a, w)
        u_bar = np.convolve(a_bar, w_bar)
        return self.trim(u_bar), a_bar, w_bar

    def ntt_intt(self, a_bar, w_bar):
        #np.array(ntt(a_bar, prime=self.prime))
        #np.array(ntt(w_bar, prime=self.prime))
        prod = np.array(ntt(a_bar, prime=p.prime))*np.array(ntt(w_bar, prime=p.prime))
        u_bar = np.array(intt(prod, prime=p.prime))
        return self.trim(u_bar)

      

In [4]:
a = np.random.randint(30, size=(p.con_size, p.con_size), dtype='int32')
w = np.array([[1,2], [3,4]], dtype='int32')

con = ConVolution()
u_bar, a_bar, w_bar = con.con1d(a, w)
print(f"Original 2D-Convolution Output: \n{con.con2d(a, w)}")
print(f"1D-Convolution Output: \n{u_bar}")
print(f"NTT/INTT Output: \n{con.ntt_intt(a_bar, w_bar)}")

Original 2D-Convolution Output: 
[[ 39 136 142 140 230 155 104 185 213]
 [140 111  71  99 180 103 125 168 112]
 [171 126 105 172 178 105 155 201 211]
 [178 203 160 205 197 173 127 175 162]
 [127 168 169 119 142 138  65 157 132]
 [193 195 161  90  93  89 126 162 173]
 [183 133 175 104  90 142 110  95 197]
 [137 187 164  76 113 188 149 150 154]
 [214 176 165 170 141 118 151 219 170]]
1D-Convolution Output: 
[[ 39 136 142 140 230 155 104 185 213]
 [140 111  71  99 180 103 125 168 112]
 [171 126 105 172 178 105 155 201 211]
 [178 203 160 205 197 173 127 175 162]
 [127 168 169 119 142 138  65 157 132]
 [193 195 161  90  93  89 126 162 173]
 [183 133 175 104  90 142 110  95 197]
 [137 187 164  76 113 188 149 150 154]
 [214 176 165 170 141 118 151 219 170]]
NTT/INTT Output: 
[[ 39 136 142 140 230 155 104 185 213]
 [140 111  71  99 180 103 125 168 112]
 [171 126 105 172 178 105 155 201 211]
 [178 203 160 205 197 173 127 175 162]
 [127 168 169 119 142 138  65 157 132]
 [193 195 161  90  93  89 

In [5]:
""""
def main():
    print(a)
    print(w)
    a_bar = a.flatten()[::-1] 
    print(a_bar)
    w_bar = np.zeros((p.con_size, p.con_size), dtype='int32')
    w_bar[0:p.kernel_size,0:p.kernel_size] = w
    print(w_bar)
    w_bar = w_bar.flatten()
    print(w_bar)
    u_bar = np.convolve(a_bar, w_bar)
    print(u_bar)
    c=u_bar[(p.con_size*(p.kernel_size-1)+p.kernel_size-2):(p.con_size**2)][::-1]
    print(c)
    result = c.reshape((p.out_size,p.con_size))[:,0:p.out_size]
    print(result)

if __name__ == "__main__":
    main()
""""

SyntaxError: unterminated string literal (detected at line 21) (453292700.py, line 21)